import {
  LucideActivity,
  LucideArrowRight,
  LucideBan,
  LucideBell,
  LucideCalendar,
  LucideCar,
  LucideChevronLeft,
  LucideChevronRight,
  LucideCircleCheck,
  LucideClock,
  LucideCreditCard,
  LucideDollarSign,
  LucideEye,
  LucideEyeOff,
  LucideImage,
  LucideLayoutGrid,
  LucideLock,
  LucideLogOut,
  LucideMail,
  LucideMapPin,
  LucideMoon,
  LucideNavigation,
  LucidePencil,
  LucideScan,
  LucideSearch,
  LucideShield,
  LucideSmartphone,
  LucideStar,
  LucideSun,
  LucideUserRound,
  LucideWarehouse,
  LucideX,
  LucideZap,
  provideLucideIcons,
} from '@lucide/angular';

export const APP_ICONS = [
  LucideActivity,
  LucideArrowRight,
  LucideBell,
  LucideCalendar,
  LucideCar,
  LucideChevronLeft,
  LucideChevronRight,
  LucideCircleCheck,
  LucideClock,
  LucideCreditCard,
  LucideDollarSign,
  LucideEye,
  LucideEyeOff,
  LucideImage,
  LucideLayoutGrid,
  LucideLock,
  LucideLogOut,
  LucideMail,
  LucideMapPin,
  LucideMoon,
  LucideNavigation,
  LucidePencil,
  LucideScan,
  LucideSearch,
  LucideShield,
  LucideSmartphone,
  LucideStar,
  LucideSun,
  LucideUserRound,
  LucideWarehouse,
  LucideX,
  LucideZap,
  LucideBan
] as const;

export function provideAppIcons() {
  return provideLucideIcons(...APP_ICONS);
}
